services:
  nexus-sdlc-docs:
    image: ghcr.io/loskylp/nexus-sdlc-docs:latest
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nexus-sdlc-docs-prod.rule=Host(`nexus-sdlc.nxlabs.cc`)"
      - "traefik.http.routers.nexus-sdlc-docs-prod.tls.certresolver=letsencrypt"
      - "traefik.http.routers.nexus-sdlc-docs-prod.entrypoints=websecure"
      - "com.centurylinklabs.watchtower.enable=true"
      - "kuma.nexus-sdlc-docs.http.name=Nexus SDLC Docs"
      - "kuma.nexus-sdlc-docs.http.url=https://nexus-sdlc.nxlabs.cc"
    networks:
      - traefik

networks:
  traefik:
    external: true
